import type { Scene } from "./types";

export const SCENES: Scene[] = [
  {
    id: "citrus-gator",
    name: "Citrus Gator",
    tagline: "Sunny I-95. Gators. It rains bananas.",
    accent: "#f4c430",
    kind: "florida",
    voice: "ev",
    hasManual: false,
    idleRpm: 0,
    redline: 18000,
    sky: ["#1ea0ff", "#ffe9a0"],
  },
  {
    id: "inverter",
    name: "Inverter",
    tagline: "Pure inverter whistle that climbs fast.",
    accent: "#ff6a1a",
    kind: "clean-ev",
    voice: "ev",
    hasManual: false,
    idleRpm: 0,
    redline: 18000,
    sky: ["#0a1014", "#c5d4d0"],
  },
  {
    id: "halo-drift",
    name: "Halo Drift",
    tagline: "Ship inverter, a resonance that keeps rising.",
    accent: "#6ad4ff",
    kind: "space",
    voice: "space",
    hasManual: false,
    idleRpm: 0,
    redline: 14000,
    sky: ["#05060e", "#24185a"],
  },
  {
    id: "tape-rain",
    name: "Tape Rain",
    tagline: "Beats under the rain, engine felt not seen.",
    accent: "#7fb8a8",
    kind: "rain",
    voice: "muffled",
    hasManual: false,
    idleRpm: 640,
    redline: 5600,
    sky: ["#12161c", "#2a3844"],
  },
  {
    id: "forge-v8",
    name: "Forge V8",
    tagline: "Big-block rumble, low then metallic.",
    accent: "#ff4a38",
    kind: "night-road",
    voice: "v8",
    hasManual: true,
    idleRpm: 780,
    redline: 7200,
    sky: ["#0b0c12", "#3a1810"],
  },
  {
    id: "signal-bloom",
    name: "Signal Bloom",
    tagline: "Detuned synth, a filter that sweeps hard.",
    accent: "#e84dff",
    kind: "neon-city",
    voice: "synth",
    hasManual: true,
    idleRpm: 900,
    redline: 7800,
    sky: ["#0c0614", "#3a1450"],
  },
  {
    id: "white-pass",
    name: "White Pass",
    tagline: "A pinched six in thin mountain air.",
    accent: "#8fc7ea",
    kind: "snow",
    voice: "i6",
    hasManual: true,
    idleRpm: 850,
    redline: 7400,
    sky: ["#9eb8cc", "#eef4fa"],
  },
  {
    id: "copper-wash",
    name: "Copper Wash",
    tagline: "Dusty torque, heat-soaked and grainy.",
    accent: "#e08a2a",
    kind: "desert",
    voice: "v8",
    hasManual: true,
    idleRpm: 700,
    redline: 6200,
    sky: ["#6a2e0e", "#f2c07a"],
  },
  {
    id: "paper-lantern",
    name: "Paper Lantern",
    tagline: "Pagoda dusk, petals on the tarmac.",
    accent: "#ff7eb6",
    kind: "lantern",
    voice: "i6",
    hasManual: true,
    idleRpm: 820,
    redline: 7600,
    sky: ["#140814", "#6a2040"],
  },
];


export const DEFAULT_SCENE_ID = "citrus-gator";

export function sceneById(id: string): Scene {
  return SCENES.find((s) => s.id === id) ?? SCENES[0]!;
}
