import type { MusicTrack, Scene } from "./types";

export const SCENES: Scene[] = [
  {
    id: "forge-v8",
    name: "Forge V8",
    tagline: "Big-block rumble, low then metallic.",
    accent: "#ff4a38",
    kind: "night-road",
    voice: "v8",
    hasMusic: false,
    hasManual: true,
    idleRpm: 780,
    redline: 7200,
    sky: ["#14161c", "#2a120e"],
  },
  {
    id: "signal-bloom",
    name: "Signal Bloom",
    tagline: "Detuned synth, a filter that sweeps hard.",
    accent: "#e84dff",
    kind: "neon-city",
    voice: "synth",
    hasMusic: false,
    hasManual: true,
    idleRpm: 900,
    redline: 7800,
    sky: ["#120818", "#2a1038"],
  },
  {
    id: "white-pass",
    name: "White Pass",
    tagline: "A pinched six in thin mountain air.",
    accent: "#8fc7ea",
    kind: "snow",
    voice: "i6",
    hasMusic: false,
    hasManual: true,
    idleRpm: 850,
    redline: 7400,
    sky: ["#8aa4b8", "#d7e4ee"],
  },
  {
    id: "copper-wash",
    name: "Copper Wash",
    tagline: "Dusty torque, heat-soaked and grainy.",
    accent: "#e08a2a",
    kind: "desert",
    voice: "v8",
    hasMusic: false,
    hasManual: true,
    idleRpm: 700,
    redline: 6200,
    sky: ["#c45a1a", "#f0c07a"],
  },
  {
    id: "tape-rain",
    name: "Tape Rain",
    tagline: "Beats under the rain, engine felt not seen.",
    accent: "#7fb8a8",
    kind: "rain",
    voice: "muffled",
    hasMusic: true,
    hasManual: false,
    idleRpm: 640,
    redline: 5600,
    sky: ["#1a2228", "#3a4a55"],
  },
  {
    id: "inverter",
    name: "Inverter",
    tagline: "Pure inverter whistle that climbs fast.",
    accent: "#ff6a1a",
    kind: "clean-ev",
    voice: "ev",
    hasMusic: false,
    hasManual: false,
    idleRpm: 0,
    redline: 18000,
    sky: ["#101318", "#1c2430"],
  },
  {
    id: "halo-drift",
    name: "Halo Drift",
    tagline: "Ship inverter, a resonance that keeps rising.",
    accent: "#6ad4ff",
    kind: "space",
    voice: "space",
    hasMusic: false,
    hasManual: false,
    idleRpm: 0,
    redline: 14000,
    sky: ["#070814", "#1a1040"],
  },
  {
    id: "paper-lantern",
    name: "Paper Lantern",
    tagline: "Pagoda dusk, petals on the tarmac.",
    accent: "#ff7eb6",
    kind: "lantern",
    voice: "i6",
    hasMusic: true,
    hasManual: true,
    idleRpm: 820,
    redline: 7600,
    sky: ["#1a0e18", "#4a1830"],
  },
  {
    id: "citrus-gator",
    name: "Citrus Gator",
    tagline: "Sunny I-95. Gators. It rains bananas.",
    accent: "#f4c430",
    kind: "florida",
    voice: "ev",
    hasMusic: false,
    hasManual: false,
    idleRpm: 0,
    redline: 18000,
    sky: ["#47b7ff", "#ffe58a"],
  },
  {
    id: "xing-ghost",
    name: "Xing Ghost",
    tagline: "Grade crossing, cyan boxes, a sudden brake.",
    accent: "#3ee0ff",
    kind: "xing",
    voice: "ev",
    hasMusic: false,
    hasManual: false,
    idleRpm: 0,
    redline: 16000,
    sky: ["#070b14", "#173044"],
  },
];

export const DEFAULT_SCENE_ID = "forge-v8";

export function sceneById(id: string): Scene {
  return SCENES.find((s) => s.id === id) ?? SCENES[0]!;
}

export const TRACKS: MusicTrack[] = [
  { id: "stoop-dusk", title: "Stoop Dusk", seed: 18, bpm: 84 },
  { id: "kitchen-light", title: "Kitchen Light", seed: 7, bpm: 76 },
  { id: "overpass-glow", title: "Overpass Glow", seed: 23, bpm: 92 },
  { id: "sink-at-3", title: "Sink at 3", seed: 4, bpm: 70 },
  { id: "terrace-breeze", title: "Terrace Breeze", seed: 11, bpm: 88 },
  { id: "debug-loop", title: "Debug Loop", seed: 31, bpm: 96 },
  { id: "lantern-waltz", title: "Lantern Waltz", seed: 9, bpm: 72 },
  { id: "after-rain", title: "After Rain", seed: 15, bpm: 80 },
];
